name = "sml_io"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
sml = "^0.1.0-dev"

[[pins]]
sml = { path='../sml' }

[build-switches]
"*".ada_version = "Ada2022"
"*".style_checks = [
  "-gnaty3",
  "-gnatyM120",
  "-gnatyB",
  "-gnatyl",
  "-gnatya",
  "-gnatyO"
]

[[actions]]
type = "test"
name = "build-tests"
command = ["alr", "exec", "--", "gprbuild", "-p", "-P", "test/test_all.gpr", "-j0"]

[[actions]]
type = "test"
name = "run-tests"
command = ["bin/test_io"]
