name = "sml_io"
description = "SML file I/O utilities (spec in SPARK; body not)"
version = "0.1.0"

authors = ["Rebecca Wise"]
maintainers = ["Rebecca Wise <rebecca@berkeleynerd.com>"]
maintainers-logins = ["berkeleynerd"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://git.idril.is/rebecca/sml_io"
tags = ["sml", "io", "spark", "utilities"]
project-files = ["sml_io.gpr"]

[[depends-on]]
sml = "=0.1.0"

[build-switches]
"*".ada_version = "Ada2022"
"*".style_checks = [
  "-gnaty3",
  "-gnatyM120",
  "-gnatyB",
  "-gnatyl",
  "-gnatya",
  "-gnatyO"
]

[gpr-externals]
SML_IO_LIBRARY_TYPE = ["static", "relocatable", "static-pic"]

[gpr-set-externals]
SML_IO_LIBRARY_TYPE = "static"

[[actions]]
type = "test"
name = "build-tests"
command = ["alr", "exec", "--", "gprbuild", "-p", "-P", "test_io.gpr", "-j0"]

[[actions]]
type = "test"
name = "run-tests"
command = ["bin/test_io"]
